name: dishplease_app
description: Restaurant reviews you can trust by people you know.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  amplify_flutter: 0.6.10
  amplify_datastore: 0.6.10
  amplify_auth_cognito: 0.6.10
  amplify_authenticator: 0.2.4
  amplify_api: 0.6.10
  phosphor_flutter: ^1.4.0
  iconsax: ^0.0.8
  cached_network_image: ^3.0.0
  flutter_svg: ^1.1.6
  image_picker: ^0.8.6+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
  #
  fonts:
    - family: Mada
      fonts:
        - asset: assets/fonts/mada/Mada-Black.ttf
        - asset: assets/fonts/mada/Mada-Bold.ttf
        - asset: assets/fonts/mada/Mada-ExtraLight.ttf
        - asset: assets/fonts/mada/Mada-Light.ttf
        - asset: assets/fonts/mada/Mada-Medium.ttf
        - asset: assets/fonts/mada/Mada-Regular.ttf
        - asset: assets/fonts/mada/Mada-SemiBold.ttf
    - family: Roboto
      fonts:
        - asset: assets/fonts/roboto/Roboto-Black.ttf
        - asset: assets/fonts/roboto/Roboto-Bold.ttf
        - asset: assets/fonts/roboto/Roboto-Light.ttf
        - asset: assets/fonts/roboto/Roboto-Medium.ttf
        - asset: assets/fonts/roboto/Roboto-Regular.ttf
        - asset: assets/fonts/roboto/Roboto-Thin.ttf
    - family: Mogra
      fonts:
        - asset: assets/fonts/Mogra/Mogra-Regular.ttf

    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans/OpenSans-Bold.ttf
