class TextConst {
  static const String restaurant = "Restaurant";
  static const String enterRestaurant = "Enter a Restaurant";
  static const String takeAgain = "Take Again";
  static const String next = "Next";
  static const String rating = "Rating";
  static const String back = "Back";
  static const String post = "Post";
  static const String zupas = "Zupas";
  static const String doYouRecommend = "Do you recommend it?";
  static const String areYouSure = "Are you sure you want to\ndiscard changes?";
  static const String discard = "Discard";
  static const String no = "No";
  static const String insertText = "Insret Text...";
  static const String writeReview = "Write a Review";
  static const String clickHereToTakePic = "Click here to take Picture";
  static const String hiresBig = "Hires Big H";
  static const String twok = "2K";
  static const String fiveSixTwo = "562";
  static const String twoHundread = "200";
  static const String visits = "Visits";
  static const String recommend = "Recommend";
  static const String review = "Review";
  static const String info = "Info";
  static const String phoneNumber = "801-555-1234";
  static const String Hoursmf = "Hours:\nM-F11AM-8PM\nS 11AM-10PM";
  static const String address = "425 S 700 E,\nSalt Lake City,\nUT 84102";
  static const String eaten = "Eaten";
  static const String like = "Like";
  static const String dishList = "DishList";
  static const String friends = "Friends";
  static const String top = "Top";
  static const String provoUtah = "Provo, Utah";
  static const String yungTwyman = "Yung Twyman";
  static const String zupasIsClassic =
      "Zupas is a classic. THe strawberry is a nice touch. Highly recommend the soup and sandwhich combo";
  static const String takePictureUsingGallrey = "Take Picture Using Gallrey";
  static const String takePictureUsingCamera = "Take Picture Using Camera";
}
